openapi: 3.0.0
info:
  version: 1.0.0
  title: 🤝 Activity
  description: Paths and components
  contact:
    email: parkerkrhoyt@gmail.com  
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
tags:
- name: 🤝 Activity
  description: Different types of developer activities
paths:
  /activity:
    get:
      tags:
      - 🤝 Activity
      summary: Read all available activities
      operationId: getActivities
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
    post:
      tags:
      - 🤝 Activity
      summary: Create a new activity type
      operationId: createActivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Sleeping
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'   
  /activity/{id}:        
    parameters:
    - name: id
      in: path
      description: ID of specific activity type
      required: true
      schema:
        type: string
        format: uuid      
    get:
      tags:
      - 🤝 Activity
      summary: Read specific activity by ID
      operationId: getActivityByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'      
    put:
      tags:
      - 🤝 Activity
      summary: Update specific activity by ID
      operationId: updateActivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Sleeping
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    delete:
      tags:
      - 🤝 Activity
      summary: Delete specific activity by ID
      operationId: deleteActivityByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid                                                              
components:
  schemas:
    Activity:
      required:
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
          example: Sleeping
          