openapi: 3.0.0
info:
  version: 1.0.0
  title: ️🖥️ Developer
  description: Paths and components
  contact:
    email: parkerkrhoyt@gmail.com
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
tags:
- name: 🖥️ Developer
  description: Individual developers - and advocates
paths:
  /developer:
    get:
      tags:
      - 🖥️ Developer
      summary: Read all developers
      operationId: getDevelopers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Developer'
    post:
      tags:
      - 🖥️ Developer
      summary: Create a new developer
      operationId: createDeveloper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Monty Burns
                email:
                  type: string
                  example: smithers@burns.com
                description:
                  type: string
                  example: Excellent!
                image:
                  type: string
                  example: http://something.com
                location:
                  type: string
                  example: Armonk, NY
                latitude:
                  type: number
                  format: float
                  example: 41.1328412
                longitude:
                  type: number
                  format: float
                  example: -73.7492039
                public:
                  type: integer
                  example: 0                  
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
  /developer/{id}:
    parameters:
    - name: id
      in: path
      description: ID field for desired developer
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Read specific developer by ID
      operationId: getDeveloperByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
    put:
      tags:
      - 🖥️ Developer
      summary: Update specific developer by ID
      operationId: updateDeveloper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Monty Burns
                email:
                  type: string
                  example: smithers@burns.com
                description:
                  type: string
                  example: Excellent!
                image:
                  type: string
                  example: http://something.com
                location:
                  type: string
                  example: Armonk, NY
                latitude:
                  type: number
                  format: float
                  example: 41.1328412
                longitude:
                  type: number
                  format: float
                  example: -73.7492039
                public:
                  type: integer
                  example: 0                  
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
    delete:
      tags:
      - 🖥️ Developer
      summary: Delete specific developer by ID
      operationId: deleteDeveloperByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /developer/{id}/note:
    parameters:
    - name: id
      in: path
      description: ID field for desired developer
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Get notes associated with a developer by their ID
      operationId: getDeveloperNotesByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    developer_id:
                      type: string
                      format: uuid
                    activity_id:
                      type: string
                      format: uuid
                    activity_name:
                      type: string
                      example: Conference
                    full_text:
                      type: string
                      example: 'IBM was here.'
  /developer/{id}/organization:
    parameters:
    - name: id
      in: path
      description: ID field for desired developer
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Get organizations associated with a developer by their ID
      operationId: getDeveloperOrganizationsByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    name:
                      type: string
                      example: 'IBM'
    post:
      tags:
      - 🖥️ Developer
      summary: Associate a specific developer with an organization
      operationId: createDeveloperOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: string
                  format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  developer_id:
                    type: string
                    format: uuid
                  organization_id:
                    type: string
                    format: uuid
  /developer/organization/{id}:
    parameters:
    - name: id
      in: path
      description: ID field for desired organization
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Get developers associated with a specific organization
      operationId: getDeveloperOrganization
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    name:
                      type: string
                      example: Kevin Hoyt
                    email:
                      type: string
                      example: krhoyt@us.ibm.com
                    description:
                      type: string
                      example: Some dude at IBM.
                    image:
                      type: string
                      example: http://something.com
                    location:
                      type: string
                      example: Armonk, NY
                    latitude:
                      type: number
                      format: float
                      example: 41.1328412
                    longitude:
                      type: number
                      format: float
                      example: -73.7492039
                    public:
                      type: integer
                      example: 0                     
  /developer/{id}/role:
    parameters:
    - name: id
      in: path
      description: ID field for desired role
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Get role associated with a developer by their ID
      operationId: getDeveloperRolesByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    name:
                      type: string
                      example: Engineer
    post:
      tags:
      - 🖥️ Developer
      summary: Associate a specific developer with an role
      operationId: createDeveloperRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role_id:
                  type: string
                  format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  developer_id:
                    type: string
                    format: uuid
                  role_id:
                    type: string
                    format: uuid
  /developer/role/{id}:
    parameters:
    - name: id
      in: path
      description: ID field for desired role
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖥️ Developer
      summary: Get developers associated with a specific role
      operationId: getDeveloperRole
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    name:
                      type: string
                      example: Kevin Hoyt
                    email:
                      type: string
                      example: krhoyt@us.ibm.com
                    description:
                      type: string
                      example: Some dude at IBM.
                    image:
                      type: string
                      example: http://something.com
                    location:
                      type: string
                      example: Armonk, NY
                    latitude:
                      type: number
                      format: float
                      example: 41.1328412
                    longitude:
                      type: number
                      format: float
                      example: -73.7492039
                    public:
                      type: integer
                      example: 0                                            
components:
  schemas:
    Developer:
      required:
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
          example: Monty Burns
        email:
          type: string
          example: smithers@burns.com
        description:
          type: string
          example: Excellent!
        image:
          type: string
          example: http://something.com
        location:
          type: string
          example: Armonk, NY
        latitude:
          type: number
          format: float
          example: 41.1328412
        longitude:
          type: number
          format: float
          example: -73.7492039
        public:
          type: integer
          example: 0
