openapi: 3.0.0
info:
  version: 1.0.0
  title: ️🖥️ 📝 Developer Note
  description: Paths and components
  contact:
    email: parkerkrhoyt@gmail.com  
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
tags:
- name: ️🖥️ 📝 Developer Note
  description: Notes associated with developer activities
paths:
  /developer/note:
    get:
      tags:
      - ️🖥️ 📝 Developer Note
      summary: Read all available notes
      operationId: getDeveloperNotes
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeveloperNote'
    post:
      tags:
      - ️🖥️ 📝 Developer Note
      summary: Create a new note for a developer
      operationId: createDeveloperNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                developer_id:
                  type: string
                  format: uuid
                activity_id:
                  type: string
                  format: uuid
                full_text:
                  type: string
                  example: Somewhere over the rainbow.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  developer_id:
                    type: string
                    format: uuid
                  activity_id:
                    type: string
                    format: uuid
                  activity_name:
                    type: string
                    example: Conference
                  full_text:
                    type: string
                    example: Somewhere over the rainbow.
  /developer/note/{id}:        
    parameters:
    - name: id
      in: path
      description: ID of a specific developer note
      required: true
      schema:
        type: string
        format: uuid      
    get:
      tags:
      - ️🖥️ 📝 Developer Note
      summary: Read specific developer note by ID
      operationId: getDeveloperNoteByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeveloperNote'      
    put:
      tags:
      - ️🖥️ 📝 Developer Note
      summary: Update specific note by ID
      operationId: updateDeveloperNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                developer_id:
                  type: string
                  format: uuid
                activity_id:
                  type: string
                  format: uuid
                full_text:
                  type: string
                  example: Somewhere over the rainbow.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeveloperNote'
    delete:
      tags:
      - ️🖥️ 📝 Developer Note
      summary: Delete specific note by ID
      operationId: deleteDeveloperNoteByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid                                                              
components:
  schemas:
    DeveloperNote:
      required:
      - developer_id
      - activity_id
      - full_text
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        developer_id:
          type: string
          format: uuid
        activity_id:
          type: string
          format: uuid
        full_text:
          type: string
          example: Somewhere over the rainbow.
          