openapi: 3.0.0
info:
  version: 1.0.0
  title: 🥑 Avocado
  description: 'Developer Relations means relating to developers. There are millions of developers. How do you relate to them all? What are your metrics? Where do you even get started? Avocado is an out-of-the-box developer relations system, with your success at heart. ❤️️'
  contact:
    email: parkerkrhoyt@gmail.com
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
tags:
- name: 🤝 Activity
  description: Different types of developer activities
- name: 🏷️ Label
  description: Logical groupings of developers (tagging)
- name: 🖥️ Developer
  description: Individual developers - and advocates
- name: ️🖥️ 📝 Developer Note
  description: Notes associated with developer activities
- name: 🖼️ Media
  description: Media (image files) associated with content aggregation
- name: 📓 Blog
  description: Blog feeds to aggregate
- name: 📓 📝 Blog Post
  description: Post made to a personal blog
- name: 🔥 Dev
  description:  DEV Community accounts to aggregate (Dev.to)
- name: 🔥 📝 Dev Post
  description: Post made to a DEV Community account
- name: 🐙 GitHub
  description: GitHub accounts to aggregate
- name: 🐙 🐱 GitHub Event
  description: Public GitHub repository interactions
- name: 🔮 Medium
  description: Medium feeds to aggregate
- name: 🔮 📝 Medium Post
  description: Post made to a Medium account
- name: 👽 Reddit
  description: Reddit accounts to aggregate  
- name: 📚 Stack Overflow
  description: Stack Overflow accounts to aggregate
- name: 📚 ✋ Stack Overflow Answer
  description: Answer made by a Stack Overflow account
- name: 📚 ❓ Stack Overflow Question
  description: Question proposed by a Stack Overflow account
- name: 🐦 Twitter
  description: Twitter accounts to aggregate
- name: 🐦 ✒️ Twitter Status
  description: Status update to a Twitter account
- name: 📺 YouTube
  description: YouTube accounts to aggregate
- name: 📺 📼 YouTube Video
  description: Video posted to a YouTube account
- name: 🗄️ Repository
  description: Specific GitHub repositories to monitor
- name: 🧠 Watson
  description: Watson machine learning features
- name: 🧰 Utliity
  description: Tools used that are unrelated to storage
paths:
  /activity:
    $ref: 'activity.yaml#/paths/~1activity'
  /activity/{id}:
    $ref: 'activity.yaml#/paths/~1activity~1{id}'
  /label:
    $ref: 'label.yaml#/paths/~1label'
  /label/{id}:
    $ref: 'label.yaml#/paths/~1label~1{id}'
  /developer:
    $ref: 'developer.yaml#/paths/~1developer'
  /developer/{id}:
    $ref: 'developer.yaml#/paths/~1developer~1{id}'
  /developer/{id}/label:
    $ref: 'developer.yaml#/paths/~1developer~1{id}~1label'
  /developer/label/{id}:
    $ref: 'developer.yaml#/paths/~1developer~1label~1{id}'
  /developer/note:
    $ref: 'developer-note.yaml#/paths/~1developer~1note'
  /developer/note/{id}:
    $ref: 'developer-note.yaml#/paths/~1developer~1note~1{id}'
  /media:
    $ref: 'media.yaml#/paths/~1media'
  /media/{id}:
    $ref: 'media.yaml#/paths/~1media~1{id}'
  /media/url/{url}:
    $ref: 'media.yaml#/paths/~1media~1url~1{url}'
  /blog:
    $ref: 'blog.yaml#/paths/~1blog'
  /blog/{id}:
    $ref: 'blog.yaml#/paths/~1blog~1{id}'
  /blog/post:
    $ref: 'blog-post.yaml#/paths/~1blog~1post'
  /blog/post/{id}:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1{id}'
  /blog/post/guid/{id}:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1guid~1{id}'
  /blog/post/{id}/media:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1{id}~1media'
  /dev:
    $ref: 'dev.yaml#/paths/~1dev'
  /dev/{id}:
    $ref: 'dev.yaml#/paths/~1dev~1{id}'
  /dev/post:
    $ref: 'dev-post.yaml#/paths/~1dev~1post'
  /dev/post/{id}:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1{id}'
  /dev/post/guid/{id}:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1guid~1{id}'
  /dev/post/{id}/media:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1{id}~1media'
  /github:
    $ref: 'github.yaml#/paths/~1github'
  /github/{id}:
    $ref: 'github.yaml#/paths/~1github~1{id}'
  /github/event:
    $ref: 'github-event.yaml#/paths/~1github~1event'
  /github/event/{id}:
    $ref: 'github-event.yaml#/paths/~1github~1event~1{id}'
  /github/event/id/{id}:
    $ref: 'github-event.yaml#/paths/~1github~1event~1id~1{id}'
  /github/activity/{login}:
    $ref: 'github.yaml#/paths/~1github~1activity~1{login}'
  /medium:
    $ref: 'medium.yaml#/paths/~1medium'
  /medium/{id}:
    $ref: 'medium.yaml#/paths/~1medium~1{id}'
  /medium/post:
    $ref: 'medium-post.yaml#/paths/~1medium~1post'
  /medium/post/{id}:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1{id}'
  /medium/post/guid/{id}:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1guid~1{id}'
  /medium/post/{id}/media:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1{id}~1media'
  /reddit:
    $ref: 'reddit.yaml#/paths/~1reddit'
  /reddit/{id}:
    $ref: 'reddit.yaml#/paths/~1reddit~1{id}'    
  /so:
    $ref: 'so.yaml#/paths/~1so'
  /so/{id}:
    $ref: 'so.yaml#/paths/~1so~1{id}'
  /so/answer:
    $ref: 'so-answer.yaml#/paths/~1so~1answer'
  /so/answer/{id}:
    $ref: 'so-answer.yaml#/paths/~1so~1answer~1{id}'
  /so/answer/id/{id}:
    $ref: 'so-answer.yaml#/paths/~1so~1answer~1id~1{id}'
  /so/answers/{user_id}:
    $ref: 'so.yaml#/paths/~1so~1answers~1{user_id}'
  /so/question/id/{id}:
    $ref: 'so-question.yaml#/paths/~1so~1question~1id~1{id}'
  /twitter:
    $ref: 'twitter.yaml#/paths/~1twitter'
  /twitter/{id}:
    $ref: 'twitter.yaml#/paths/~1twitter~1{id}'
  /twitter/timeline/{screen_name}:
    $ref: 'twitter.yaml#/paths/~1twitter~1timeline~1{screen_name}'
  /twitter/status:
    $ref: 'twitter-status.yaml#/paths/~1twitter~1status'
  /twitter/status/{id}:
    $ref: 'twitter-status.yaml#/paths/~1twitter~1status~1{id}'
  /twitter/status/id/{id}:
    $ref: 'twitter-status.yaml#/paths/~1twitter~1status~1id~1{id}'
  /twitter/status/{id}/media:
    $ref: 'twitter-status.yaml#/paths/~1twitter~1status~1{id}~1media'
  /youtube:
    $ref: 'youtube.yaml#/paths/~1youtube'
  /youtube/{id}:
    $ref: 'youtube.yaml#/paths/~1youtube~1{id}'
  /youtube/video:
    $ref: 'youtube-video.yaml#/paths/~1youtube~1video'
  /youtube/video/{id}:
    $ref: 'youtube-video.yaml#/paths/~1youtube~1video~1{id}'
  /youtube/video/guid/{id}:
    $ref: 'youtube-video.yaml#/paths/~1youtube~1video~1guid~1{id}'
  /youtube/video/duration/{video}:
    $ref: 'youtube-video.yaml#/paths/~1youtube~1video~1duration~1{video}'
  /repository:
    $ref: 'repository.yaml#/paths/~1repository'
  /repository/{id}:
    $ref: 'repository.yaml#/paths/~1repository~1{id}'
  /watson/language/{url}:
    $ref: 'watson.yaml#/paths/~1watson~1language~1{url}'
  /watson/vision/{url}:
    $ref: 'watson.yaml#/paths/~1watson~1vision~1{url}'
  /utility/images/{url}:
    $ref: 'utility.yaml#/paths/~1utility~1images~1{url}'
components:
  schemas:
    Activity:
      $ref: 'activity.yaml#/components/schemas/Activity'
    Blog:
      $ref: 'blog.yaml#/components/schemas/Blog'
    BlogPost:
      $ref: 'blog-post.yaml#/components/schemas/BlogPost'
    BlogPostMedia:
      $ref: 'blog-post.yaml#/components/schemas/BlogPostMedia'
    Dev:
      $ref: 'dev.yaml#/components/schemas/Dev'
    Developer:
      $ref: 'developer.yaml#/components/schemas/Developer'
    DeveloperNote:
      $ref: 'developer-note.yaml#/components/schemas/DeveloperNote'
    DevPost:
      $ref: 'dev-post.yaml#/components/schemas/DevPost'
    DevPostMedia:
      $ref: 'dev-post.yaml#/components/schemas/DevPostMedia'
    GitHub:
      $ref: 'github.yaml#/components/schemas/GitHub'
    GitHubEvent:
      $ref: 'github-event.yaml#/components/schemas/GitHubEvent'
    Label:
      $ref: 'label.yaml#/components/schemas/Label'
    Media:
      $ref: 'media.yaml#/components/schemas/Media'
    Medium:
      $ref: 'medium.yaml#/components/schemas/Medium'
    MediumPost:
      $ref: 'medium-post.yaml#/components/schemas/MediumPost'
    MediumPostMedia:
      $ref: 'medium-post.yaml#/components/schemas/MediumPostMedia'
    Reddit:
      $ref: 'reddit.yaml#/components/schemas/Reddit'      
    Repository:
      $ref: 'repository.yaml#/components/schemas/Repository'
    StackOverflow:
      $ref: 'so.yaml#/components/schemas/StackOverflow'
    StackOverflowAnswer:
      $ref: 'so-answer.yaml#/components/schemas/StackOverflowAnswer'
    StackOverflowQuestion:
      $ref: 'so-question.yaml#/components/schemas/StackOverflowQuestion'
    Twitter:
      $ref: 'twitter.yaml#/components/schemas/Twitter'
    TwitterStatus:
      $ref: 'twitter-status.yaml#/components/schemas/TwitterStatus'
    TwitterStatusMedia:
      $ref: 'twitter-status.yaml#/components/schemas/TwitterStatusMedia'
    YouTube:
      $ref: 'youtube.yaml#/components/schemas/YouTube'
    YouTubeVideo:
      $ref: 'youtube-video.yaml#/components/schemas/YouTubeVideo'
