openapi: 3.0.0
info:
  version: 1.0.0
  title: 🥑 Avocado
  description: 'Developer Relations means relating to developers. There are millions of developers. How do you relate to them all? What are your metrics? Where do you even get started? Avocado is an out-of-the-box developer relations system, with your success at heart. ❤️️'
  contact:
    email: parkerkrhoyt@gmail.com
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:8000/api
tags:
- name: 🏷️ Label
  description: Logical groupings of developers (tagging)
- name: 🖥️ Developer
  description: Individual developers - and advocates
- name: 🖼️ Media
  description: Media (image files) associated with content aggregation
- name: 📓 Blog
  description: Blog feeds to aggregate
- name: 📓 📝 Blog Post
  description: Post made to a personal blog
- name: 🔥 Dev
  description:  DEV Community accounts to aggregate (Dev.to)
- name: 🔥 📝 Dev Post
  description: Post made to a DEV Community account
- name: 🔮 Medium
  description: Medium feeds to aggregate
- name: 🔮 📝 Medium Post
  description: Post made to a Medium account
- name: 🧠 Watson
  description: Watson machine learning features
- name: 🧰 Utliity
  description: Tools used that are unrelated to storage
paths:
  /label:
    $ref: 'label.yaml#/paths/~1label'
  /label/{id}:
    $ref: 'label.yaml#/paths/~1label~1{id}'
  /developer:
    $ref: 'developer.yaml#/paths/~1developer'
  /developer/{id}:
    $ref: 'developer.yaml#/paths/~1developer~1{id}'
  /developer/{id}/label:
    $ref: 'developer.yaml#/paths/~1developer~1{id}~1label'
  /developer/label/{id}:
    $ref: 'developer.yaml#/paths/~1developer~1label~1{id}'
  /media:
    $ref: 'media.yaml#/paths/~1media'
  /media/{id}:
    $ref: 'media.yaml#/paths/~1media~1{id}'
  /media/url/{url}:
    $ref: 'media.yaml#/paths/~1media~1url~1{url}'
  /blog:
    $ref: 'blog.yaml#/paths/~1blog'
  /blog/{id}:
    $ref: 'blog.yaml#/paths/~1blog~1{id}'
  /blog/post:
    $ref: 'blog-post.yaml#/paths/~1blog~1post'
  /blog/post/{id}:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1{id}'
  /blog/post/guid/{id}:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1guid~1{id}'
  /blog/post/{id}/media:
    $ref: 'blog-post.yaml#/paths/~1blog~1post~1{id}~1media'
  /dev:
    $ref: 'dev.yaml#/paths/~1dev'
  /dev/{id}:
    $ref: 'dev.yaml#/paths/~1dev~1{id}'
  /dev/post:
    $ref: 'dev-post.yaml#/paths/~1dev~1post'
  /dev/post/{id}:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1{id}'
  /dev/post/guid/{id}:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1guid~1{id}'
  /dev/post/{id}/media:
    $ref: 'dev-post.yaml#/paths/~1dev~1post~1{id}~1media'
  /medium:
    $ref: 'medium.yaml#/paths/~1medium'
  /medium/{id}:
    $ref: 'medium.yaml#/paths/~1medium~1{id}'
  /medium/post:
    $ref: 'medium-post.yaml#/paths/~1medium~1post'
  /medium/post/{id}:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1{id}'
  /medium/post/guid/{id}:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1guid~1{id}'
  /medium/post/{id}/media:
    $ref: 'medium-post.yaml#/paths/~1medium~1post~1{id}~1media'
  /watson/language/{url}:
    $ref: 'watson.yaml#/paths/~1watson~1language~1{url}'
  /watson/vision/{url}:
    $ref: 'watson.yaml#/paths/~1watson~1vision~1{url}'
  /utility/images/{url}:
    $ref: 'utility.yaml#/paths/~1utility~1images~1{url}'
components:
  schemas:
    Label:
      $ref: 'label.yaml#/components/schemas/Label'
    Developer:
      $ref: 'developer.yaml#/components/schemas/Developer'
    Media:
      $ref: 'media.yaml#/components/schemas/Media'
    Blog:
      $ref: 'blog.yaml#/components/schemas/Blog'
    BlogPost:
      $ref: 'blog-post.yaml#/components/schemas/BlogPost'
    BlogPostMedia:
      $ref: 'blog-post.yaml#/components/schemas/BlogPostMedia'
    Dev:
      $ref: 'dev.yaml#/components/schemas/Dev'
    DevPost:
      $ref: 'dev-post.yaml#/components/schemas/DevPost'
    DevPostMedia:
      $ref: 'dev-post.yaml#/components/schemas/DevPostMedia'
    Medium:
      $ref: 'medium.yaml#/components/schemas/Medium'
    MediumPost:
      $ref: 'medium-post.yaml#/components/schemas/MediumPost'
    MediumPostMedia:
      $ref: 'medium-post.yaml#/components/schemas/MediumPostMedia'
